name: grocery_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  carousel_slider: ^4.2.1
  google_fonts:
  country_list_pick:
  otp_text_field:
  geocoding:
  google_places_flutter:
  geolocator:
  flutter_polyline_points:
  google_maps_flutter:
  location:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/commons/
    - images/icons/
    - images/diary/
    - images/fruits/
    - images/meat/
    - images/vegetables/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
